---
name: Trigger

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  _:
    runs-on: ubuntu-latest
    steps:
      - name: Generate branch name
        run: echo BRANCH_NAME=branch-$(date +%s) >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Change file
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b ${{ env.BRANCH_NAME}}
          date | tee last-change.txt
          git add last-change.txt
          git commit -m "Make a change"
          git push origin HEAD:${{ env.BRANCH_NAME }} -f
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: ${{ env.BRANCH_NAME }},
              base: "main",
              title: "Automatic pull request"
            })
            console.log(pr)
      - uses: ./.github/workflows/pull-request.yaml@main
        with:
          pull-request: 1
