---
name: Trigger

on:
  push:
    branches:
      - main

jobs:
  _:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Change file
        run: |
          date | tee last-change.txt
          git add last-change.txt
          git commit -m "Make a change"
          gh pr create --base ${{ github.head_ref }} --head example-pr --title "Example Pull Request"
